---
- name: Populate service facts
  service_facts:

- name: Get liagentd status
  debug:
    msg: "Log Insight agent is {{ ansible_facts.services['liagentd.service'].state }}"
  register: liagentstatus
  ignore_errors: yes

- name: Agent check.
  debug:
    msg: "vRLI agent is already installed so skipping installation."
  when: liagentstatus is success

- name: Begin vRLI agent install.
  block:
  - name: vRLI agent install.
    debug:
      msg: "vRLI agent will now be installed."

  - name: Downloading vRLI agent locally
      get_url:
        url: {{ liserver_uri }}
        dest: /tmp/liagent.deb
        validate_certs: no

  - name: Install package
    apt:
      deb: /tmp/liagent.deb
      state: present
    register: installed

  - name: Setup INI options
    ini_file:
      path: /var/lib/loginsight-agent/liagent.ini
      section: "{{ item.section }}"
      option: "{{ item.option }}"
      value: "{{ item.value }}"
      create: no
      state: present
      no_extra_spaces: yes
    with_items:
      - { section: 'server', option: 'hostname', value: '{{ liserver }}'}
      - { section: 'server', option: 'proto', value: '{{ liproto }}'}
      - { section: 'server', option: 'ssl', value: '{{ lissl }}'}
      - { section: 'update', option: 'auto_update', value: '{{ liauto_update }}'}

  - name: Remove temporary file
    file:
      path: /tmp/liagent.deb
      state: absent
  when:
    - liagentstatus is failed